modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="tes"
version="1.0.0"
displayName="The Elder Scrolls"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Dale_Hat"
description='''
Dale's TES Port
'''

[[dependencies.tes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.tes]]
    modId="lotr"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


